apiVersion: v1
kind: Deployment
metadata:
  name: hello-mcp-server
spec:
  type: container
  container:
    image:
      build: .
    command: ["python3", "-u", "mcp_server.py"]
    configSchema:
      type: object
      properties:
        TEST_VAR:
          type: string
          title: "Test Variable"
          description: "Just a test"