apiVersion: v1
kind: Deployment
metadata:
  name: hello-mcp-server
spec:
  type: container
  container:
    image:
      build: .
    command: ["python", "mcp_server.py"]
    
    configSchema:
      type: object
      required: ["GEMINI_API_KEY"]
      properties:
        GEMINI_API_KEY:
          type: string
          title: "Gemini API Key"
          description: "Your Google Gemini API Key for PDF summarization"