apiVersion: v1
kind: Deployment
metadata:
  name: my-mcp-server  # Change this to your server name
spec:
  type: container
  container:
    image:
      build: .
    command: ["python3", "-u", "mcp_server.py"]
    
    # Optional: Add configuration for API keys
    configSchema:
      type: object
      properties:
        API_KEY:
          type: string
          title: "API Key"
          description: "Your API key"
        # Add more config options as needed